FROM ghcr.io/santhosh-p653/base:latest

RUN pip install --no-cache-dir \
    transformers \
    face-detection \
    Pillow \
    numpy \
    opencv-python-headless

LABEL org.opencontainers.image.source=https://github.com/Santhosh-p653/ml-base-images
