name: Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push base
        run: |
          docker build -t ghcr.io/santhosh-p653/base:latest ./base
          docker push ghcr.io/santhosh-p653/base:latest

  build-dl:
    runs-on: ubuntu-latest
    needs: build-base

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push dl
        run: |
          docker build -t ghcr.io/santhosh-p653/dl:latest ./dl
          docker push ghcr.io/santhosh-p653/dl:latest

  build-ml:
    runs-on: ubuntu-latest
    needs: build-base

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ml
        run: |
          docker build -t ghcr.io/santhosh-p653/ml:latest ./ml
          docker push ghcr.io/santhosh-p653/ml:latest
